# Generated by Django 5.1.7 on 2025-03-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="owner",
            field=models.IntegerField(default=2, verbose_name="Venue Owner"),
        ),
    ]
