# Generated by Django 5.1.7 on 2025-03-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_venue_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="venueimage",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="venue",
            name="owner",
            field=models.IntegerField(default=1, verbose_name="Venue Owner"),
        ),
    ]
